; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:upesy_wroom]
upload_port = klo-kalle.fritz.box # 192.168.1.118 #

platform = espressif32
board = esp32doit-devkit-v1
monitor_speed = 115200
framework = arduino
extra_scripts = pre:lib/ProjectUtils-esp32/copy_lib_data.py
upload_protocol = espota
lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    ayushsharma82/WebSerial @ ^1.1.0
    sstaub/NTP@^1.6


[env:esp32-s3-supermini]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:lib/ProjectUtils-esp32/copy_lib_data.py

board_build.arduino.memory_type = qio_qspi
board_build.flash_mode = qio
board_build.psram_type = qio
board_build.filesystem = littlefs

board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
board_build.partitions = default.csv

build_flags = 
   -DBOARD_HAS_PSRAM
   -DARDUINO_USB_MODE=1
   -DARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200

lib_deps =
    me-no-dev/AsyncTCP @ ^1.1.1
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    ayushsharma82/WebSerial @ ^1.1.0
    sstaub/NTP@^1.6
